// fetch all news items
export const FETCH_ALL_NEWS_REQUEST = 'FETCH_ALL_NEWS_REQUEST'
export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS'
export const FETCH_ALL_NEWS_FAILURE = 'FETCH_ALL_NEWS_FAILURE'

// FETCH ALL EVENTS Constants
export const FETCH_ALL_EVENTS_REQUEST = 'FETCH_ALL_EVENTS_REQUEST'
export const FETCH_ALL_EVENTS_SUCCESS = 'FETCH_ALL_EVENTS_SUCCESS'
export const FETCH_ALL_EVENTS_FAILURE = 'FETCH_ALL_EVENTS_FAILURE'

// constant for fetching carousel
export const FETCH_ALL_CAROUSEL_REQUEST = 'FETCH_ALL_CAROUSEL_REQUEST'
export const FETCH_ALL_CAROUSEL_SUCCESS = 'FETCH_ALL_CAROUSEL_SUCCESS'
export const FETCH_ALL_CAROUSEL_FAILURE = 'FETCH_ALL_CAROUSEL_FAILURE'

// constant for Adding carousel
export const ADD_CAROUSEL_REQUEST = 'ADD_CAROUSEL_REQUEST'
export const ADD_CAROUSEL_SUCCESS = 'ADD_CAROUSEL_SUCCESS'
export const ADD_CAROUSEL_FAILURE = 'ADD_CAROUSEL_FAILURE'

// constant for EDITING carousel
export const EDIT_CAROUSEL_REQUEST = 'EDIT_CAROUSEL_REQUEST'
export const EDIT_CAROUSEL_SUCCESS = 'EDIT_CAROUSEL_SUCCESS'
export const EDIT_CAROUSEL_FAILURE = 'EDIT_CAROUSEL_FAILURE'
